version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        labels:
            slim4.spartoi.php: "Spartoi PHP"
        build:
            context: ./_docker/dockerfiles/
            dockerfile: Dockerfile
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
#        environment:
#            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - ./logs:/var/www/logs
    db:
        labels:
            slim4.spartoi.mariadb: "Spartoi MariaDB"
        image: mariadb
        restart: always
        ports:
            - ${MYSQL_PORT:-3306}:${MYSQL_PORT:-3306}
        volumes:
            - ./_docker/mysql/mysql:/var/lib/mysql
            - ./_docker/mysql/initdb.d:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=pwd
            - MYSQL_DATABASE=${MYSQL_DBNAME:-test}
            - MYSQL_USER=${MYSQL_USER:-user}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:-pwd}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        labels:
            slim4.spartoi.phpmyadmin: "Spartoi phpMyAdmin"
        volumes:
            - ./_docker/phpmyadmin/sessions:/sessions
            - ./_docker/phpmyadmin/conf/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST:-db}
            - PMA_USER=${MYSQL_USER:-user}
            - PMA_PASSWORD=${MYSQL_PASSWORD:-pwd}
        ports:
            - 8081:80